---
- name: Add epel
  hosts: centos8
  tasks:
    - name: Enable EPEL repository
      yum:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
        state: present
      register: status
      until: status is succeeded
      become: true
