---
- name: Check requested major version for Corretto
  fail:
    msg: "Supported versions of Amazon Corretto only 8 and 11"
  when:
    - java_major_version|int != 8
    - java_major_version|int != 11

# Installing on Amazon Linux 2 from repo
# Amazon Corretto 8 specific
# https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/amazon-linux-install.html
- name: Prepare Amazon Linux 2 for Corretto 8
  block:
    - name: Enable the yum repository in Amazon Linux 2
      command: warn=no amazon-linux-extras enable corretto8

    - name: Clean repo metadata
      command: warn=no yum clean metadata
  when:
    - transport == "repositories"
    - ansible_distribution == "Amazon"
    - ansible_distribution_version == "2"
    - java_major_version|int == 8

# Install in any case via Yum
- name: 'Install Corretto {{ java_major_version }}'
  include_tasks: RedHat.yml
