---
- name: debug java_package
  debug:
    var: java_package

- name: debug jdk_package
  debug:
    var: jdk_package

- name: debug java_major_version
  debug:
    var: java_major_version

- name: debug adoptopenjdk_impl
  debug:
    var: adoptopenjdk_impl

- name: Add repository for AdoptOpenJDK
  yum_repository:
    name: AdoptOpenJDK
    description: AdoptOpenJDK
    baseurl: http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/7/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

- name: Install java packages
  yum:
    name: '{{ (transport == "repositories") | ternary(jdk_package, java_artifact) }}'
    state: present
  register: package_install
  until: package_install is succeeded
