---
# Installing from repo on Amazon Linux 2
- name: Check requested major version for Corretto
  fail:
    msg: "Supported versions of Amazon Corretto only 8 and 11"
  when:
    - java_major_version|int != 8
    - java_major_version|int != 11

- name: Check if Amazon Linux 2
  fail:
    msg: "You can use Yum Package Manager only on Amazon Linux 2"
  when:
    - ansible_distribution != "Amazon"
    - ansible_distribution_version != "2"

# Amazon Corretto 8 specific
# https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/amazon-linux-install.html
- name: Enable the yum repository in Amazon Linux 2
  shell: amazon-linux-extras enable corretto8
  when: java_major_version|int == 8

# Amazon Corretto 8 specific
- name: Clean repo metadata
  shell: yum clean metadata
  when: java_major_version|int == 8

# Amazon Corretto 8 specific
# Somehow java-1.8.0-amazon-corretto-devel package can't be installed via Ansible yum module
- name: 'Install Corretto {{ java_major_version }}'
  shell: "yum install {{ jdk_package }} -y"
  when: java_major_version|int == 8

- name: 'Install Corretto {{ java_major_version }}'
  yum:
    name: '{{ jdk_package }}'
    state: present
  when: java_major_version|int == 11
  register: package_install
  until: package_install is succeeded
