---
- name: debug java_path
  debug:
    var: java_path

- name: debug java_folder
  debug:
    var: java_folder

- name: debug java_major_version
  debug:
    var: java_major_version

- name: debug java_tarball_install
  debug:
    var: java_tarball_install

- name: debug java_folder_repo_transport
  debug:
    var: java_folder_repo_transport

- name: debug java_folder_ext_transport
  debug:
    var: java_folder_ext_transport

- name: Mkdir for java installation
  file:
    path: '{{ java_path }}/{{ java_folder }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 'Install java {{ java_full_version }}'
  unarchive:
    src: '{{ java_artifact }}'
    dest: '{{ java_path }}/{{ java_folder }}'
    remote_src: true
    owner: root
    group: root
    mode: 0755
    extra_opts: [--strip-components=1]
    creates: '{{ java_path }}/{{ java_folder }}/bin/'
