---
- name: debug java_artifact
  debug:
    var: java_artifact

- name: debug java_path
  debug:
    var: java_path

- name: debug java_folder
  debug:
    var: java_folder

- name: Install java packages
  win_package:
    path: '{{ java_artifact }}'
    # product_id: '{{ java_product_id }}'
    state: present
    arguments: '/s INSTALLDIR="{{ java_path }}\{{ java_folder }}"'
    creates_path: '{{ java_path }}\{{ java_folder }}'
