---
- name: debug java_artifact
  debug:
    var: java_artifact

- name: debug java_product_id
  debug:
    var: java_product_id

- name: debug java_product_id_ver
  debug:
    var: java_product_id_ver

- name: debug java_folder
  debug:
    var: java_folder

- name: debug java_major_version
  debug:
    var: java_major_version

- name: debug java_minor_version
  debug:
    var: java_minor_version

- name: debug java_folder_ext_transport
  debug:
    var: java_folder_ext_transport

- name: debug java_artifact_basename
  debug:
    var: java_artifact_basename

- name: debug parts
  debug:
    var: parts

- name: Mkdir for java installation
  win_file:
    path: '{{ java_path }}'
    state: directory

- name: 'Install java {{ java_full_version }}'
  win_unzip:
    src: '{{ java_artifact }}'
    dest: '{{ java_path }}'
    creates: '{{ java_path }}\{{ java_folder }}'
